{% set name = "cadnaPromise" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}



source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f27785f9d9e15e4e27b0447663a6dcf4cd1c9d52841a2a4454ac677c923646e8

build:
  noarch: python
  number: 1

requirements:
  build:
    - colorlog
    - python >=3.6
    - colorama
    - tqdm
    - regex
    - pytest
    - pytest-cov
    - pyyaml

  run:
    - python >=3.6


test:
  requires:
    - pip
    - pytest
    - pytest-cov
    
  files:
    - run_examples.py
  imports:
    - cadnaPromise
  requires:
    - pip
  commands:
    - cd examples
    - pip check
    - pytest

    

about:
  home: https://github.com/PEQUAN/cadnaPromise
  summary: 'Software for simulating arbitrary precision and precision tuning.'
  license: GNU General Public
  license_family: GNU General Public
  license_file: LICENSE
  dev_url: https://github.com/PEQUAN/cadnaPromise

extra:
  recipe-maintainers:
    - chenxinye
    - fjezequel
    - thilaire

