{% set name = "cadnaPromise" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f27785f9d9e15e4e27b0447663a6dcf4cd1c9d52841a2a4454ac677c923646e8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0


  
requirements:
  build:
    - colorlog
    - python >=3.6
    - colorama
    - tqdm
    - regex
    - pytest
    - pytest-cov
    - pyyaml
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}



test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - cadnaPromise
    

about:
  home: https://github.com/PEQUAN/cadnaPromise
  summary: 'Software for simulating arbitrary precision and precision tuning.'
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  dev_url: https://github.com/PEQUAN/cadnaPromise

extra:
  recipe-maintainers:
    - chenxinye
