{% set name = "cadnaPromise" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f27785f9d9e15e4e27b0447663a6dcf4cd1c9d52841a2a4454ac677c923646e8

build:
  number: 0
  noarch: python {{ python_min }}
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  build:
    - python >={{ python_min }}
    - pip
    - colorlog
    - python >=3.6
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - colorlog
    - python >=3.6
    - colorama
    - tqdm
    - regex
    - pytest
    - pytest-cov
    - pyyaml


test:
  imports:
    - cadnaPromise
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
  source_files:
    - examples/test_examples.py
  commands:
      pip install --upgrade pip
      pip install pytest-cov
      pip install build
      python3 -m build
      pip install -U setuptools
      pip install .
      cd cadnaPromise/cadna
      bash run_unix.sh
      export CADNA_PATH=`pwd`
      cd lib
      bash run_unix.sh
      cd ../../..
      cd examples
      pytest test_examples.py 
    
about:
  home: https://github.com/PEQUAN/cadnaPromise
  summary: 'Software for simulating arbitrary precision and precision tuning.'
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  dev_url: https://github.com/PEQUAN/cadnaPromise

extra:
  recipe-maintainers:
    - chenxinye
